### ISSUE TITLE
Missing Title

### ISSUE THREAD

**Issue by izenn** [blawar/titledb#31]
Physical release, 0100662013D12000, Shadows of Adam, v0

**Comment by grimson73** [comment]
It seems like the database is stuck of missing recent updates.
For example the latest Mario Kart update 'Mario Kart 8 Deluxe [0100152000022800][v1114112]'

https://raw.githubusercontent.com/blawar/titledb/master/versions.txt

No complaints but just a notify of this issue.

**Comment by blawar** [comment]
sabrent ssd failure, working to get it replaced without losing data / reinstalling everything.

**Comment by mspykerez** [comment]
Seems like titles.json is not being generated properly (recent updates show as 'null')
versions.json looks OK

**Comment by mspykerez** [comment]
Yes this one https://tinfoil.media/repo/db/titles.json
but I also generated one with NUT to check if it was any different and it got the same problem.

**Comment by jonasmare** [comment]
titles.json does seem to not be updated, example, the site lists Hogwarts Legacy v1 update but in titles.json it says only v0
versions.json lists the correct v1 update thou

Also I notice that there is some games missing from tinfoi.io like 'The Last Faith' and 'Alien Death Mob' both of which released before the date of the last discovered title.
The Last Faith at least appears on versions.json, Alien Death Mob on the other hand doesn't seem to be listed anywhere as far i can tell.

**Comment by hgh32** [comment]
Breath of the Wild DLC has four versions
01007EF00011F001/01007EF00011F002
v0,v65536,v131072,v196608
I found v0 somewhere
v65536, v131072 may have been permanently lost

**Comment by blawar** [comment]
> Breath of the Wild DLC has four versions 01007EF00011F001/01007EF00011F002 v0,v65536,v131072,v196608 I found v0 somewhere v65536, v131072 may have been permanently lost

196608 came out in 2018, they probably were missed.  Its also possible that Nintendo simply never released them. I have seen them skip patch version numbers before. I assume this happens when a release fails QA and they have to go back and fix a bug before release.

**Comment by hgh32** [comment]
> 196608 came out in 2018, they probably were missed. Its also possible that Nintendo simply never released them. I have seen them skip patch version numbers before. I assume this happens when a release fails QA and they have to go back and fix a bug before release.

But this title did have four versions and was released
You can see them on speedrunning videos
Because its version number is displayed in the lower right corner of the title menu
v0=1.0.0,v65536=2.0.0,v131072=2.1.0,v196608=3.0.0
This is the version of the title I think it corresponds to

Also yes they are keen on "skipping"
https://www.nintendo.co.jp/support/wiiu/soft/alzj/update/index.html
This is the botw update history they gave
1.3.2 (v458752) was skipped between v0-v786432
But in fact they did publish to cdn
This also happens with totk, through data mining I found out that it may have a 1.0.1 version

**Comment by mspykerez** [comment]
@hgh32 could be one of those updates that came bundle with the physical cartridge and never made to CDN.

AFAIK tinfoil only grabs from CDN thus misses some physical versions that sometimes have different titleid, example being:
Owlboy 0100E570094E8000
Metaverse Keeper 0100AC601A844000
Crisis Wing 0100E47016C8C000

Some of these can be found listed at nswdb.com

**Comment by blawar** [comment]
> @hgh32 could be one of those updates that came bundle with the physical cartridge and never made to CDN.
> 
> AFAIK tinfoil only grabs from CDN and misses some physical versions that sometimes have different titleid, example being: Owlboy 0100E570094E8000 Metaverse Keeper 0100AC601A844000 Crisis Wing 0100E47016C8C000
> 
> Some of these can be found listed at nswdb.com

With regards to the BOTW update, I remember installing at least one of those missing DLC versions. Nintendo released the update soon after the DLC (expansion pass) was released. The problem is, the switch wasnt hacked until a year later, so any updates that were not the latest around summer 2018 are likely lost, and unfortunately these old DLC versions fall into that category.

**Comment by jonasmare** [comment]
Why would titles that have physical releases not be on CDN?
I mean that even games that are released physically get updates every now and then so even if they have a different ID they would still be on CDN in order for the Switch pick up updates and whatnot, am I wrong?

**Comment by mspykerez** [comment]
The repo is being updated quite regularly as of late :thumbsup:
